image: gcc:latest

variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - dependencies
  - build

before_script:
  - apt-get update -qq
  - apt-get install -y make cmake unzip curl
  - apt-get install -y libgl1-mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

build_dependencies:
  stage: dependencies
  script:
    - ./scripts/build_dependencies.sh
  cache:
    key: dependencies-v1
    paths:
      - dependencies/
  artifacts:
    paths:
      - dependencies/
    expire_in: 1 week

build_release:
  stage: build
  dependencies:
    - build_dependencies
  script:
    - make release
  artifacts:
    name: "release-build"
    paths:
      - bin/Release/
    expire_in: 1 week

build_debug:
  stage: build
  dependencies:
    - build_dependencies
  script:
    - make debug
  artifacts:
    name: "debug-build"
    paths:
      - bin/Debug/
    expire_in: 3 days
