image: gcc:latest

variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - build

before_script:
  - apt-get update -qq
  - apt-get install -y make cmake unzip curl
  - apt-get install -y libgl1-mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
  - apt-get install -y libfreeimage-dev libglfw3-dev
  - ./scripts/build_dependencies.sh

build_release:
  stage: build
  script:
    - CI=true make release
  artifacts:
    name: "release-build"
    paths:
      - bin/Release/
    expire_in: 1 week

build_debug:
  stage: build
  script:
    - CI=true make debug
  artifacts:
    name: "debug-build"
    paths:
      - bin/Debug/
    expire_in: 3 days
